services:
  postgres:
    container_name: MOTO_DB_POSTGRES
    image: "postgres:17"
    environment:
      POSTGRES_USER: "kirillBuglak"
      POSTGRES_PASSWORD: "xPost_4!5o0Oh@"
      POSTGRES_DB: "moto"
      PGDATA: /data/postgres
    volumes:
       - /home/kir/Files/postgres/moto/data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kirillBuglak -d moto"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  mongo:
    container_name: MOTO_DB_MONGO
    image: mongo:8.0.3
    restart: unless-stopped
   # environment:
     # MONGO_INITDB_ROOT_USERNAME: kirillBuglak
     # MONGO_INITDB_ROOT_PASSWORD: xMong_5&9Il1Hk&
     # MONGO_INITDB_DATABASE: moto
    volumes:
       - /home/kir/Files/mongo/moto/data:/data/db
    ports:
      - 27017:27017
    networks:
      - app_net

  mongo-express:
    container_name: MONGO_UI
    image: mongo-express
    restart: always
    ports:
      - 28081:8081
    networks:
      - app_net
    environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: kirillBuglak
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: xMong_5&9Il1Hk&
    #  ME_CONFIG_MONGODB_URL: mongodb://kirillBuglak:moto@mongo:27017
      ME_CONFIG_BASICAUTH: false

  redis:
    container_name: MOTO_REDIS
    image: redis:latest
    command: redis-server --appendonly yes --requirepass redis123
    ports:
      - 6379:6379
    volumes:
      - /home/kir/Files/postgres/moto/redis_data:/data
    networks:
      - app_net

  grafana:
    container_name: MOTO_GRAFANA
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - 3001:3000
    volumes:
      - /home/kir/Files/postgres/moto/grafana_data:/var/lib/grafana
    networks:
      - app_net

  zookeeper:
    container_name: MOTO_ZOO
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - app_net

  kafka:
    container_name: MOTO_KAFKA
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - app_net

  kafka-ui:
    container_name: MOTO_KAFKA_UI
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: Kafka
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - app_net

  jenkins:
    container_name: MOTO_JENKINS
#    image: jenkins/jenkins:lts
    build:
      context: .
      dockerfile: JenkinsDockerfile
    ports:
      - "8081:8080"
      - "5000:5000"
    volumes:
      - /home/kir/Files/jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_net
    restart: unless-stopped

  core:
    container_name: MOTO_CORE
    image: core:v1.0
    depends_on:
      - redis
      - mongo
      - postgres
    ports:
      - 8443:8443
      - 5001:5001
    volumes:
      - /home/kir/IdeaProjects/moto/core/dockerConf:/app/config
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5001
    networks:
      - app_net

  messaging:
    container_name: MOTO_MESSAGING
    image: messaging:v1.0
    depends_on:
      - core
      - kafka
    ports:
      - 8444:8444
      - 5002:5002
    volumes:
      - /home/kir/IdeaProjects/moto/messaging/dockerConf:/app/config
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5002
    networks:
      - app_net

  frontend:
    container_name: MOTO_FRONT
    image: moto-front:v1.0
    depends_on:
      - core
    ports:
      - 3000:80
    networks:
      - app_net

  prometheus:
    container_name: MOTO_PROMETHEUS
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_net
  
networks:
  app_net:
    driver: bridge
