server:
  port: 8444
  ssl:
    key-store: keystore.p12
    key-store-password: pass
    key-alias: 1
    key-store-type: PKCS12
    enabled: true
    enabled-protocols: TLSv1.3 # openssl s_client -connect localhost:8444 -tls1_2 - for tls version check


spring:
  kafka:
    bootstrap-servers: 172.20.0.9:9093
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.default.type: kb.moto.model.kafka.EmailKafkaMessage
        spring.json.trusted.packages: "kb.moto.model.kafka"
    template:
      default-topic: just
  mail:
    host: smtp.gmail.com
    port: 587
    username: some@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/moto?currentSchema=messages
    username: kirillBuglak
    password: xPost_4!5o0Oh@
